### ISSUE TITLE
Run script conflicts with installation scripts

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#105]
the assumption of the current run.sh is that the fixture files are checked into the repo in a known location. Run.sh then copies them over to ~/Chromatic/Fixtures/Entwined.

the assumption of the current install_fixtures.sh is that the someone will manually run the script on a folder of fixture description files (the installation). Install_fixtures.sh then generates the fixture files (which are not checked into the repo) and copies them over to ~/Chromatic/Fixtures/Entwined.

These two control paths are incompatible.
@bbulkow, leaving to you to resolve. I'm guessing you're just going to want to remove the fixture copy line from run.sh. The question about whether we want the fixtures files checked into the repo is interesting though.

**Comment by bbulkow** [comment]
Yes, agreed.

**Comment by bbulkow** [comment]
Resolved. The runs and installs no longer copy out of the checked in directory.
