### ISSUE TITLE
Plugin control : start stop record

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#110]
I could see that since the platform is taking on the capabilities of doing playback, I would expect there should be methods accessible to the plugin which would specify the file and start and stop and record, giving the plugin full control. 

This would allow us true external control for doing things like uploading a ~~pattern file~~ recording file remotely and switch to it, which has been a requested feature

**Comment by mcslee** [comment]
Echo what the autoplay code does.

```
Recordings recordings = findModulator(lx, Recordings.class);
```

The `Recordings` object has public methods for the things you want:
```
recordings.openRecording(lx, file);
```
https://github.com/squaredproject/Entwined/blob/chromatik/chromatik/src/main/java/entwined/modulator/Recordings.java#L203

```
recordings.playRecording(lx);
```
https://github.com/squaredproject/Entwined/blob/chromatik/chromatik/src/main/java/entwined/modulator/Recordings.java#L224

Stop can be achieved by generic LX API method `lx.engine.clips.stopClips()`

> This would allow us true external control for doing things like uploading a pattern file remotely and switch to it, which has been a requested feature

Assuming by "pattern file" you mean a recording here - but let me know if I've misunderstood.

**Comment by bbulkow** [comment]
Cool, looks right
