### ISSUE TITLE
Hue Global Modulator needs to come back

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#118]
Lots of patterns (twister!) depend on the global hue modulator, and look really bland without it

**Comment by mcslee** [comment]
If you want this back, click on the color box in the left pane GLOBAL Color Palette. Change this color from `Fixed` to `Hue Cycle` mode - with whatever cycle time you desire. Will then work just like it did before, any pattern querying `lx.engine.palette.getHuef()` will get that rotating hue.

<img width="283" alt="Screen Shot 2022-11-13 at 8 36 37 PM" src="https://user-images.githubusercontent.com/597850/201576312-3a66b266-b89b-4a6e-b378-e3ac80f98dcd.png">

**Comment by bbulkow** [comment]
Validated! Thanks.
