### ISSUE TITLE
Master brightness doesn't have any effect

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#119]
Turn the slider up and down, nothing happens

**Comment by mcslee** [comment]
The master fader only effects the pixels that are output over the network, e.g. via DDP, not the preview shown in the UI. Idea here is to be able to dim a physical sculpture to desired level, while still seeing full contrast of what you're animating on-screen.

If you want the UI to reflect brightness level changes, you can put a Dynamics effect on the master bus.

**Comment by bbulkow** [comment]
I think that's going to cause a lot of confusion. People will look at the screen and look at the sculpture and tell me it's broken. But your choice.

Are there any other UI elements besides the obvious "output" / "live" which effect output and not the screen?

**Comment by mcslee** [comment]
I guess I could possibly make this a preference. But it's been a common case historically that close-view LEDs can be way-the-heck-too-bright and a sculpture gets run at a modest brightness setting. But the laptop screen is not way-too-bright and you can't see what you're doing that way.

Only other output-only stuff is in the OUTPUT box on the left pane MODEL tab:
<img width="191" alt="Screen Shot 2022-11-13 at 8 52 24 PM" src="https://user-images.githubusercontent.com/597850/201578068-cdcd9df0-1075-4626-93d1-2c7017555685.png">

I definitely recommend  playing with the gamma control, find that things often look better with a gamma curve in the 1.5-2.5 range for typical LEDs.

**Comment by mcslee** [comment]
I would just add to that - I don't recommend using the APC40 master fader, or the master fader in general, as an "animation" effect in terms of content. I think of that one like the volume knob on your amplifier.

If you want to make a piece of music that has oscillating volume, put that in the music itself so it plays back that way, rather than turning your volume knob up and down as the music plays.

And this way, you retain the ability to tweak an appropriate master brightness on your sculpture.

Maybe a moot point in this case since with the diffusing boxes it probably is fine to run at 100% hardware brightness - but throwing this out there anyways as the philosophy of that control.

**Comment by bbulkow** [comment]
I see charlie often want to pull down the brightness on the entire sculpture when a set is starting or ending, but leave it alone during the set and use only the channel values, so we typically do use it that way or mostly that way and can train people that way.

The major surprise is literally the only knob (and a large knob) that doesn't have any effect on the simulator. All someone has to do in recording a set (without the sculpture) is leave it down, and try to play back the recording, and call me saying the sculpture is broken. Or live leave the knob down and say the sculpture is broken.

Are you saying the master doesn't get recorded in a playback file? Because then we can set it in the project file, and have it unaffected by recording playback, which would make sense in the use you're talking about. 

We'll see how often I get called for the sculpture not working because it's working fine on the screen. Or maybe they'll figure it out.

**Comment by mcslee** [comment]
Recordings actually do not include the master fader for this reason. It's considered an output property (as reflected in code, e.g. it's on the output object at `lx.engine.output.brightness`) - not on the `lx.engine.mixer` object, so it's not automated.

Still could confuse people but at least the gotcha you list above shouldn't happen. But along the same lines you should ensure people know that they shouldn't  think they can work that fader up and down as part of recording a set.

**Comment by bbulkow** [comment]
Sounds good. I will let you know user feedback in a few weeks, I think,.
