### ISSUE TITLE
License error: Service won't start first time (and doesn't fail)

### ISSUE THREAD

**Issue by bbulkow** [squaredproject/Entwined#123]
When running as a service on the raspberry pi, at boot time the system throws a lot of this error:

Nov 13 22:54:04 chromatik headless.sh[516]: [LX 2022/11/13 22:54:04] Unexpected error in device loop entwined.pattern.jake_lampack.AcidTrip: Cannot read field "cubes" because "entwined.core.CubeManager.theCubeManager" >
Nov 13 22:54:04 chromatik headless.sh[516]: java.lang.NullPointerException: Cannot read field "cubes" because "entwined.core.CubeManager.theCubeManager" is null

which is because of the following:
Nov 13 22:52:30 chromatik systemd[1]: Started Chromatic Headless.
Nov 13 22:52:32 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:32] Starting Chromatik version 0.4.2-SNAPSHOT
Nov 13 22:52:32 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:32] Running java 17.0.5 Eclipse Adoptium Linux 5.15.76-v8+ aarch64
Nov 13 22:52:32 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:32] License hardware signature does not match machine, may need to reaut>Nov 13 22:52:32 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:32] License signature did not verify, possibly corrupted or out of date?
Nov 13 22:52:32 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:32] Unrecognized CLI argument, ignoring: --disable-prefences
Nov 13 22:52:32 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:32] Headless CLI flag set, running without UI...
Nov 13 22:52:33 chromatik headless.sh[516]: [LX 2022/11/13 22:52:33] Loading package content from: /home/pi/Chromatik/Packages/entwined-0.0.1-SN>Nov 13 22:52:34 chromatik headless.sh[516]: [Chromatik 2022/11/13 22:52:34] Opening initial project file: /home/pi/Chromatik/Projects/entwined.l>Nov 13 22:52:36 chromatik headless.sh[516]: [LX 2022/11/13 22:52:36] Project loaded successfully from /home/pi/Chromatik/Projects/entwined.lxp
Nov 13 22:52:36 chromatik headless.sh[516]: [LX 2022/11/13 22:52:36] LXEngine.ExecutorService starting...
Nov 13 22:52:36 chromatik headless.sh[516]: [LX 2022/11/13 22:52:36] Unexpected error in device loop entwined.pattern.kyle_fleming.Rain: Cannot >Nov 13 22:52:36 chromatik headless.sh[516]: java.lang.NullPointerException: Cannot read field "cubes" because "entwined.core.CubeManager.theCube>Nov 13 22:52:36 chromatik headless.sh[516]:         at entwined.core.CubeManager.getCube(CubeManager.java:29)

but the system doesn't fail out, which means the process doesn't try to restart later, it just doesn't run in the way that the project file expects because it doesn't have the license file.

Easiest suggestion would be to fail with a bad license file and tell people to remove it, instead of continuing and running without the necessary features.

Also tried a succession of different changes to the wanted targets, which didn't work
*adding a 10 second sleep* to autoplay does work, although 5 seconds does not

**Comment by bbulkow** [comment]
The other point would be what linux Wanted line in the systemd would be necessary. I tried after both users and network, two of the most common, that would seem to have information needed for a license (which user am I and network information).

**Comment by mcslee** [comment]
Hrm, yeah. I have added a `--require-license` CLI argument.

In terms of what's missing that's causing it not to match the license file, it would be looking for network interface information, MAC addresses in particular. That should be available here: https://github.com/squaredproject/Entwined/commit/ec81edaea66078ee437781cba49bcaabf73f1058

Let me know if that helps sort this out?

Also noticed a typo in `--disable-preferences` in `headless.sh` which I fixed here.
https://github.com/squaredproject/Entwined/commit/dc1ee1f09caccbe9d77bae76f028ebb18dcda9d5

**Comment by bbulkow** [comment]
Since I asked for networking to be up, it's hard to imagine this is not available. I might say "random mac address" but it works after 10 seconds. What interface are you using to find the mac addresses? Are you using all of them, or some? I might imagine lo0 and maybe eth0 are up ... Although honestly require-license should hide a multitude of sins :-)

In the service of fail-fast, can the process halt if the .lxp file is specified but not found? Not sure if it does atm, or maybe it was the plugin preventing restart.....

**Comment by mcslee** [comment]
Should accept any network interface with a valid mac address.

```
for (NetworkInterface ni : java.util.Collections.list(NetworkInterface.getNetworkInterfaces())) {
        byte[] test = ni.getHardwareAddress();
        if (test != null) {
```

This is what the relevant code is looking for.

**Comment by bbulkow** [comment]
It is possible the license was generated with interface X, and only interface Y is available? Or is it generated for all MACs available at the time?

I think we've stopped using external wifi adapters, thankfully. We used to have a bag of them; I think we've moved to all external wifi routers so only Eth0 will be available in production, but when we generate licenses we'll probably be over wifi......

**Comment by bbulkow** [comment]
I'll do some stackoverflow about what that attaches to. There's a SIGIOCTL that's commonly used and very durable across a large number of *nix, and most tools reach for the same thing (eg ethtool) so I should be able to see the value right before chromatik is launched

**Comment by mcslee** [comment]
License should contain all valid interfaces available at the time of generation. Take a look at your `~/Chromatik/.license` file and you should be able to see what's in there.

Feel free to re-authorize if you think your license is wonked, there are more authorizations allocated for you.

Maybe to debug you could make a little Java program that just loops that `getNetworkInterfaces()` call and println or log it somewhere to see what you're getting back?

**Comment by mcslee** [comment]
To expand on the debugging suggestion - I mean run that debug program as a service, not just CLI - to see if during service initialization the JVM is returning something different.

Also feel like I vaguely recall running into weirdnesses with starting Java things as a service on RPi for an art piece, and ended up resorting to using a `crontab @reboot` job - feels a touch gross/hacky but seemed to work fine.

**Comment by bbulkow** [comment]
Added the --require-license to the startup script, will try on an rpi, and will do some debugging about what's happening during startup. Partially done.

**Comment by bbulkow** [comment]
Tested. Had to also change the startup script to retry after 3 seconds, otherwise the service would choke.
Did not figure out why the license file doesn't work originally.
