### ISSUE TITLE
Won't start on my Mac (newlx)

### ISSUE THREAD

**Issue by yozlet** [squaredproject/Entwined#47]
Warning: though I'm a _somewhat_ experienced developer, I haven't done any Java in over a decade.

* running macOS Catalina (10.15.7)
* downloaded and installed Java 8 from Oracle, which turned out to be a JRE, then it wanted me to log in to oracle.com for a JDK, so fuck that noise
* installed `AdoptOpenJDK8` from homebrew cask instead
* on first `gradlew` run, it installed Gradle 6.7

Then, crash city:

```
➜  ./gradlew run

> Task :run
[LX 2021/01/30 13:28:11] Initializing LX version 0.2.1
2021-01-30 13:28:17.886 java[13112:297875] Apple AWT Internal Exception: NSWindow drag regions should only be invalidated on the Main Thread!
2021-01-30 13:28:17.886 java[13112:297875] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff30a13b57 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff698585bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff30a3c34c -[NSException raise] + 9
        3   AppKit                              0x00007fff2dc365ec -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
        4   AppKit                              0x00007fff2dc1e052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
        5   AppKit                              0x00007fff2dc1dac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        6   libnativewindow_macosx.jnilib       0x000000012b9093fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
        7   ???                                 0x000000010608d407 0x0 + 4396209159
)
libc++abi.dylib: terminating with uncaught exception of type NSException

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 134

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by bbulkow** [comment]
Yoz, are you trying to develop patterns for the sculpture? Then you want to use processing, which is under the 'oldlx' subdirectory. Gradel is a new stream of development and is not being maintained yet. Although I am surprised it crashes, we'll not spend immediate resources looking into it (if you want to take on the 'newlx' system, which includes gradel, you're welcome to, and I suggest starting with issue #47 :-)

I thought that was covered in the README.md - is it not, or not clear enough?

If your interest is something other than authoring patterns for the existing sculpture in golden gate park, speak up.... thanks!

**Comment by yozlet** [comment]
Ah, thank you! My interest is indeed in authoring patterns, and I haven't even seen Entwined in person yet (though I hope to in the next couple of weeks). I was talking to @mizpoon earlier and she mentioned I might have a go at creating patterns. The README could be more clear but I was also skim-reading and jumping to (what I thought was) the action. I'm happy to make a PR with ideas for restructuring so it's more task oriented (e.g. "Want to make patterns? Want to work on the controller?" etc.)

**Comment by mizpoon** [comment]
Nice to see you participating Yoz!! And if you need to know important Q&A
like what a shrub is, call me xxx

**Comment by bbulkow** [comment]
Hi Yoz! I think you're missing most of the documentation (ie, we won't be restructuring - we will be pointing from the readme to the main documentation area). In order to get started, can you join our slack channel? You can ask questions of Colin who has been working with the pattern writers, and he has videos and runs livecode sessions.
