### ISSUE TITLE
Make sure interactive effect (fire) still works

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#69]
The implementation of interactive effects is somewhat different, so we need to verify that they work as desired. In particular,
we need to make sure that the compositing of interactive effects works correctly (the interactive effect should completely paint on top of the existing pixels, compositing is REPLACE for those pixels that are touched).

As far as I am told, the only interactive effect currently working is Fire

**Comment by mcslee** [comment]
Just dropping these references again as they may be useful here, the `LXColor.lerp` utility functions for replacing one color by another (e.g. painting on top of):
https://github.com/heronarts/LX/blob/dev/src/main/java/heronarts/lx/color/LXColor.java#L427

You can supply an alpha level to smooth the transition from leave-as-is to replace.
