### ISSUE TITLE
Unsaved Changes problem/IPad coordination issues

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#71]
Controlling interaction between the ipad and playback (which is to say, ipad needs to be disabled when playback occurs) means that we need to disable all of the ipad effects during playback.

Previously, the code created a set of ipad effects on the master channel that it then turned off. These effects could be the same as existing effects, they were just all in a single block and could be turned off easily.

Currently, we've attempted to consolidate effects, so it's no longer guaranteed that a) turning off ipad effects won't turn off effects that are crucial to playback, and b) ipad effects are no longer guaranteed to be in a single consolidated block.

If we go back to creating a single consolidated block (an easy solution) then we run into the problem that we will *always* be modifying the project file, and we may be adding block after block after block of ipad effects. This is bad UI and a waste of resources.

Other options - 
- tag the ipad channels so they can be found/verified/turned off
- use another mechanism to stop ipad communication. Honestly, turning off features in the engine to prevent them from being used by the ipad seems stupid - why don't we simply drop all ipad communication on the floor? Or will that cause the ipad app to behave differently?

**Comment by mcslee** [comment]
> why don't we simply drop all ipad communication on the floor? Or will that cause the ipad app to behave differently?

I haven't looked into the iPad code... is it stateful? Does the server send messages back to the iPad indicating the state of LX?

If not, then I would agree the simplest thing would be to just set a flag when in playback mode and just completely ignore the iPad input when that's the case. As long as the iPad is stateless, seems like that should be fine (seems sort of equivalent to just powering off the iPad and restarting it later, from the server's POV at least).

Agreed that this will save you adding in state-management code on the LX engine side, which risks more surface area for annoying program-state-dependent bugs.

**Comment by cswales** [comment]
Yes, that's pretty much what I've implemented, with the modification that there seem to be a few ipad commands that were previously considered legal.

There's still an issue with *stopping* running iPad effects. Stopping iPad patterns is easy - they're all on designated channels that we can just turn off. Stopping iPad effects is more difficult, since they're potentially intermixed with other effects on the master channel. My current thought is to rename the iPad effects to something that starts with iPad, so I'll be able to manage them separately from other effects that might link back to the same class.

**Comment by cswales** [comment]
I've renamed the iPad effects so I can start and stop them independently. Still need to test this.
