### ISSUE TITLE
Multiple leds per cube problem

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#73]
Some of the cubes contain more than one LEDs. According to Mark, there is a way to denote this such that LXpoints will reference cubes, rather than having two points at the same physical location.

**Comment by mcslee** [comment]
Documentation on LXF output definitions here:
https://github.com/heronarts/LXStudio/wiki/Custom-JSON-Fixtures#indexing

Specifically note the `repeat` field.

```
output: { ... start: 0, num: 10, repeat: 3 }
```

The above will construct an output that sends `30` pixels. The output will look like:
`0,0,0,1,1,1,2,2,2,...`

The `repeat` value specifies that each animated pixel in LX-land (e.g. one `LXPoint`) is repeated N times when it is output.

This seems fitting for your cubes, where they're one animated point but there are multiple LEDs inside them.

**Comment by cswales** [comment]
Fabulous. That was exactly what I was looking for.
