### ISSUE TITLE
Interactive Fire effect doesn't work properly

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#80]
The flames aren't getting generated correctly. This is probably due to some mismatch in operation between old and new utility functions, but whatever it is isn't obvious.

The problem is exacerbated by completely inscrutable calculations of the fire effect, such as 
           cBrt = EntwinedUtils.min(100, EntwinedUtils.max(0, EntwinedUtils.max(cBrt, (100 - 2 * EntwinedUtils.abs(cdata.localY - flames.get(i).decay.getValuef()) - flames.get(i).decay.getBasisf() * 25) * EntwinedUtils.min(1, 2 * (1 - flames.get(i).decay.getBasisf())) )));

and 
         color.v = EntwinedUtils.min(100, 3* (cBrt + EntwinedUtils.pow(EntwinedUtils.max(0, (height - 0.3f) / 0.7f), 0.5f) * EntwinedUtils.pow(EntwinedUtils.max(0, 0.8f - yn), 2) * 75))
         
         got help us all.

**Comment by bbulkow** [comment]
So it doesn't crash, it just doesn't look as good as it used to
