### ISSUE TITLE
Initializing interactive effects - changes project file

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#81]
One of the things I'm trying to avoid is having the program constantly complaining that the project file has changed. Along those lines, I'm also trying to prevent the entwined plugin from adding effects/channels/patterns that have already been added in the project file.

Currently interactive effects do not fulfill this requirement. I should probably do a check on the master channel for a fire effect with the name 'fire ' + piece id.

**Comment by cswales** [comment]
Okay, this is more problematic than it first appears. Each interactive effect is actually n independent effects, and there is a container class that routes messages from the outside to the appropriate independent effect. The independent effect is saved in the project file, but the containers are not. 
So when I try to restore a project that has interactive effects, the thing crashes pretty hard.
@mcslee - any suggestions here? I suppose I can rewrite the effects so that they don't depend on the containers, and also rewrite the routing to use the effect names, but that's kind of a pain in the ass.

**Comment by cswales** [comment]
After thinking about it for a bit this morning, I'm more convinced that the right thing to do is to refactor the interactive effects code. Having a container that is not an Effect, and hundreds of children that are Effects even if most of them will never be used, causes problems not only with project files, but also general UI usability (with just four possible types of effects, the number of effects in the Master channel is so great that I can't scroll without getting screen glitches. And god help you if you're actually trying to find something in there.)

So my plan is to have just *one* effect for each type of effect, and have that spin up child threads to actually change the colors as needed. Let me see what I can come up with.

**Comment by mcslee** [comment]
Yeah I definitely think refactoring this makes sense. The container-of-effects approach thing makes a mess. Each `LXEffect` should be a singular thing that contains its processing.

> So my plan is to have just one effect for each type of effect, and have that spin up child threads to actually change the colors as needed. Let me see what I can come up with.

Just confirming you don't mean threads here as in Java `Thread` right? But rather different code-paths that the effect can utilize based upon what its settings are? You definitely shouldn't be starting up new `Thread` objects for `LXEffect` processing, that should be done on-engine-thread via the `run()` method.

Looking at the code you referenced, it's very weird to me that `InteractiveEffect` takes a `Class` reference to a childClass and then constructs a new instance of it.

Why not just have those child classes extend from `InteractiveEffect` and get its functionality that way? Seems like a weird inversion of subclassing. The `newInstance()` call being made by `InteractiveEffect` just feels really wrong.

As for damping, enabling... effects all have an enabled button and parameter, `effect.enabled` - visible in the UI which you can also toggle from code if you like.

<img width="282" alt="Screen Shot 2022-11-13 at 9 38 55 PM" src="https://user-images.githubusercontent.com/597850/201583840-7b9a223a-f1a2-4348-afa0-fccb1e576629.png">

That automatically damps the `double enabledAmount` parameter passed to the `run()` method on an `LXEffect`. Default is 250ms damping for both on and off, but you can tweak those if you like via `effect.enabledDampingAttack` (for turning on) and `enabledDampingRelease` (for turning off).

**Comment by cswales** [comment]
I'm going to push back pretty hard on changing the way InteractiveEffect constructs its children. Here's one of the problems I'm trying to solve - I want to be able to take  existing effects and without making nearly any changes to them, turn them into these interactive effects. Any additional code people are required to write beyond creating a standard LXEffect is not helpful. This structure allows me to do that with effectively two lines of code - one, you change 'extends LXEffect' to 'extends TSEffect', to pick up on the change that allows the container to call run(). And two, you subclass InteractiveEffect and do nothing besides specifying the your new class you want it to be cons'ing up. 

I'm adding a certain amount of complexity in the machinery, but that's where complexity should be - not with our pattern writers.

Am I missing something? This seems like a quite elegant solution to me. 
@mcslee
